langauge: cpp
sudo: required
dist: focal

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - qt5-default
      - libsdl2-dev
      - libsdl2-image-dev
      - cppcheck
      - python

script:
  - python ./cpplint.py --filter=`cat filter_options` `ls *_src/*.cpp *_src/*.h`
  - cppcheck --enable=all ./server_src/*.cpp ./client_src/*.cpp ./common_src/*.cpp ./editor_src/*.cpp
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/TPWOLFSTEIN_tests
