langauge: cpp
sudo: required
dist: focal

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - qt5-default
      - libsdl2-dev
      - libsdl2-image-dev
      - cppcheck

script:
  - chmod +x execute.sh
  - ./execute.sh
  - cppcheck --enable=all ./server_src/*.cpp ./client_src/*.cpp ./common_src/*.cpp ./editor_src/*.cpp
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/TPWOLFSTEIN_tests
